spring.application.name=e-food-inventory-service
spring.profiles.active=dev
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8001

cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.access.key=${CLOUDINARY_ACCESS_KEY}
cloudinary.access.secret=${CLOUDINARY_ACCESS_SECRET}
folder.name.CATEGORY_IMAGE_FOLDER=${CATEGORY_FOLDER_NAME}
folder.name.SUBCATEGORY_IMAGE_FOLDER=${SUBCATEGORY_FOLDER_NAME}